server:
  port: 8080
  tomcat:
    threads:
      max: 200
      min-spare: 10
    max-connections: 10000
    accept-count: 100

spring:
  application:
    name: voting-system-spring-boot
  threads:
    virtual:
      enabled: true

logging:
  level:
    root: INFO
    com.voting: INFO
