@startuml
!include <awslib/AWSCommon>
!include <awslib/General/Users>
!include <awslib/Compute/EC2>
!include <awslib/Database/DynamoDB>
!include <awslib/ApplicationIntegration/APIGateway>
!include <awslib/SecurityIdentityCompliance/Cognito>

title Realtime Voting System

Users(client, "Devs", "Developers")

package "AWS Cloud" {
  package "Voting VPC" {
    APIGateway(gateway, "AWS Gateway", "Bot & DDoS protection")
    EC2(nginx1, "NGINX #1", "Reverse Proxy")
    EC2(app1, "Vote API #1", "Spring Boot/Kotlin")
    DynamoDB(dynamo, "DynamoDb", "Votes & audit")
    Cognito(auth, "Auth Provider", "Auth")
  }

  package "CI/CD VPC" {
    EC2(jenkins, "Jenkins", "CI/CD")
  }
}

client --> jenkins
jenkins --> gateway
gateway --> auth
gateway --> nginx1
nginx1 --> app1
app1 --> dynamo

@enduml
