@startuml
!include <awslib/AWSCommon>
!include <awslib/General/Users>
!include <awslib/Compute/EC2>
!include <awslib/Database/RDS>
!include <awslib/SecurityIdentityCompliance/WAF>
!include <awslib/SecurityIdentityCompliance/Cognito>

title Realtime Voting System

Users(client, "Users", "Web/Mobile Clients")

package "AWS Cloud" {
  package "Voting VPC" {
    WAF(waf, "AWS WAF", "Bot & DDoS protection")
    EC2(nginx1, "NGINX #1", "Reverse Proxy")
    EC2(app1, "Vote API #1", "Spring Boot/Kotlin")
    RDS(rds, "RDS", "Votes & audit")
    Cognito(auth, "Auth Provider", "Auth")
  }

  package "CI/CD VPC" {
    EC2(jenkins, "Jenkins", "CI/CD")
  }
}

client --> waf
waf --> nginx1
nginx1 --> app1
app1 --> rds
client --> auth
auth --> app1

@enduml
