bootstrap.servers=localhost:9092
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter
offset.storage.file.filename=/tmp/connect-offsets.dat
offset.flush.interval.ms=5000
plugin.path=/tmp/kafka-connect-plugins
