name=filepulse-sales-connector
connector.class=io.streamthoughts.kafka.connect.filepulse.source.FilePulseSourceConnector
tasks.max=1
fs.listing.class=io.streamthoughts.kafka.connect.filepulse.fs.LocalFSDirectoryListing
fs.listing.directory.path=/tmp/filepulse-input
fs.listing.filters=io.streamthoughts.kafka.connect.filepulse.fs.filter.RegexFileListFilter
file.filter.regex.pattern=.*\\.csv$
fs.cleanup.policy.class=io.streamthoughts.kafka.connect.filepulse.fs.clean.LogCleanupPolicy
filters=parseCSV
filters.parseCSV.type=io.streamthoughts.kafka.connect.filepulse.filter.DelimitedRowFilter
filters.parseCSV.extractColumnName=headers
filters.parseCSV.trimColumn=true
filters.parseCSV.separator=,
topic=sales.file
offset.strategy=name
